main/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns



urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('contact/', include('contact.urls')),
    path('', include('movies.urls')),
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/movies/models.py
from django.db import models
from datetime import date
from django.urls import reverse


class Category(models.Model):
    """Категории"""
    name = models.CharField("Категория", max_length=150)
    description = models.TextField("Описание")
    url = models.SlugField(max_length=160)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

class Actor(models.Model):
    """Актеры и режесеры"""
    name = models.CharField("Имя", max_length=100)
    age = models.PositiveSmallIntegerField("Возраст", default=0)
    description = models.TextField("Описание")
    image = models.ImageField("Изображение", upload_to="actors/")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('actor_detail', kwargs={"slug": self.name})

    class Meta:
        verbose_name = "Актеры и режисеры"
        verbose_name_plural = "Актеры и режиссеры"


class Genre(models.Model):
    """жанры"""
    name = models.CharField("Имя", max_length=100)
    description = models.TextField("Описание")
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Жанр"
        verbose_name_plural = "Жанры"

class Movie(models.Model):
    """Фильм"""

    title = models.CharField("Название", max_length=100)
    tagline = models.CharField("Слоган", max_length=100, default='')
    description = models.TextField("Описание")
    poster = models.ImageField("Постер", upload_to="movies/")
    year = models.PositiveSmallIntegerField("Дата выхода", default=2019)
    country = models.CharField("Страна", max_length=30)
    directors = models.ManyToManyField(Actor, verbose_name="режиссер", related_name="film_director")
    actors = models.ManyToManyField(Actor, verbose_name="актеры", related_name="film_actor")
    genres = models.ManyToManyField(Genre, verbose_name="жанры")
    world_premiere = models.DateField("Премьера в фильме", default=date.today)
    budget = models.PositiveIntegerField("Бюджет", default=0, help_text="указать сумму")
    fees_in_usa = models.PositiveIntegerField(
        "Сборы в США", default=0, help_text="указывать сумму в долларах"
    )
    fess_in_world = models.PositiveIntegerField(
        "Сборы в мире", default=0, help_text="указывать сумму в долларах"
    )
    category = models.ForeignKey(
        Category, verbose_name="Категория", on_delete=models.SET_NULL, null=True, related_name='film_category'
    )
    url = models.SlugField(max_length=160, unique=True)
    draft = models.BooleanField("Черновик", default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('movie_detail', kwargs={'slug': self.url})

    def get_rewiew(self):
        return self.rewiews_set.filter(parent__isnull=True)
    class Meta:
        verbose_name = "Фильм"
        verbose_name_plural = "Фильмы"

class MovieShots(models.Model):
    """Кадры из фильма"""
    title = models.CharField("Заголовок", max_length=100)
    description = models.TextField("Описание")
    image = models.ImageField("Изображение", upload_to="movie_shots/")
    movie = models.ForeignKey(Movie, verbose_name="Фильм", on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Кадр из фильма"
        verbose_name_plural = "Кадры из фильма"


class RatingStar(models.Model):
    """Звезда рейтинга"""
    value = models.SmallIntegerField("Значение", default=0)

    def __str__(self):
        return  f'{self.value}'

    class Meta:
        verbose_name = "Звезда рейтинга"
        verbose_name_plural = "Звезды рейтинга"
        ordering = ["-value"]

class Rating(models.Model):
    """Рейтинг"""
    ip = models.CharField("IP адрес", max_length=15)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE, verbose_name="звезда")
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name="фильм")

    def __str__(self):
        return f'{self.star} - {self.movie}'

    class Meta:
        verbose_name = "Рейтинг"
        verbose_name_plural = "Рейтинги"

class Rewiews(models.Model):
    """Отзыввы"""
    email = models.EmailField()
    name = models.CharField("Имя", max_length=100)
    text = models.TextField("Сообщение", max_length=5000)
    parent = models.ForeignKey(
        'self', verbose_name="Родитель", on_delete=models.SET_NULL, blank=True, null=True
    )
    movie = models.ForeignKey(Movie, verbose_name="фильм", on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} - {self.movie}'

    class Meta:
        verbose_name = "Отзыа"
        verbose_name_plural = "Отзывы"

main/templates/main/actor.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} {{ actor.name }} {% endblock title %}
{% block container %}
    <div class="container py-md-3">
{% endblock container %}

{% block sidebar %}
    <div class="side-bar col-lg-4">
{% endblock sidebar %}

{% block movie %}
    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="desc1-left col-md-6">
                <img src="{{ actor.image.url }}" class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent">
                    {{ movie.title }}
                </h3>
                <h5 class="editContent"></h5>
                <ul>
                    <li>
                        <span><b>Возраст:</b> {{ actor.age }} лет</span></li>
                    <li>
                        <span><b>Режиссер:</b>
                            {% for movie in actor.film_director.all %}
                                {{ movie.title }}
                            {% endfor %}
                        </span>
                    </li>
                    <li><span><b>Актер:</b>
                        {% for movie in actor.film_actor.all %}
                            {{ movie.title }}
                        {% endfor %}
                    </span>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row sub-para-w3layouts mt-5">
            <h3 class="shop-sing editContent">
                О {{ actor.name }}
            </h3>
            <p class="editContent">
                {{ actor.description|safe }}
            </p>
        </div>
    </div>
{% endblock movie %}

main/templates/main/base.html
{% extends 'base.html' %}
{% block title %} {% endblock title %}
{% block content %}
    <section class="ab-info-main py-md-5 py-4 editContent"
             style="padding-left: 3rem; padding-right: 3rem;">
        {% block container %}
            <div class="container-fluid py-md-3">
        {% endblock container %}
        <div class="row">
            {% block sidebar %}
                <div class="side-bar col-lg-3">
            {% endblock sidebar %}
            {% include 'include/sidebar.html' %}
            </div>
            {% block movie %}
            {% endblock movie %}
        </div>
        </div>
    </section>
{% endblock content %}

main/templates/main/cat_detail.html
 {% extends 'main/base.html' %}
 {% load static %}

 {% block movie %}
     <div class="left-ads-display col-lg-9">
        <div class="row">
 {% for movie in category.film_category.all %}}
              <div class="col-md-4 product-men" >
                    <div class="product-shoe-info editContent text-center mt-lg-4">
                        <div class="men-thumb-item">
                            <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
                        </div>
                        <div class="item-info-product">
                            <h4 class="">
                                <a href="{{ movie.get_absolute_url }}"
                                   class="editContent">
 {{ movie.title }}
                                </a>
                            </h4>

                            <div class="product_price">
                                <div class="grid-price">
                                    <span class="money editContent">{{ movie.tagline }}</span>
                                </div>
                            </div>
                            <ul class="stars">
                                <li><a href="#"><span class="fa fa-star"
                                                      aria-hidden="true"></span></a>
                                </li>
                                <li><a href="#"><span class="fa fa-star"
                                                      aria-hidden="true"></span></a>
                                </li>
                                <li><a href="#"><span class="fa fa-star-half-o"
                                                      aria-hidden="true"></span></a>
                                </li>
                                <li><a href="#"><span class="fa fa-star-half-o"
                                                      aria-hidden="true"></span></a>
                                </li>
                                <li><a href="#"><span class="fa fa-star-o"
                                                      aria-hidden="true"></span></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
 {% endfor %}
  <div class="grid-img-right mt-4 text-right bg bg1" >
                    {% include 'include/pagination.html' %}
  </div>
 {% endblock %}

main/templates/main/categories.html
 {% extends 'main/base.html' %}
 {% load static %}

{% block container %}
    <div class="container py-md-3">
{% endblock container %}


{% block sidebar %}
    <div class="side-bar col-lg-4">
{% endblock sidebar %}


 {% block movie %}
        {% for category in category_list %}
        <container style="background-color: gray; width: 350px; height: 200px; margin-left: 20px;">

            <div style="color: red; padding-top: 20%; padding-left: 50px;">
                <h1><a href="{% url 'cat_detail' category.name %}">{{ category.name }}</a> </h1>
                <br>
                {{ category.description }}
            </div>

        </container>
        {% endfor %}
 {% endblock %}

main/templates/main/login.html
{% extends 'main/base.html' %}
 {% load static %}

 {% block movie %}
 <h1><span style="margin-left: 50px;">Авторизация</span></h1>

   <form action="{% url 'login' %}" method="post" style="margin-top: 70px; float: left;">
        {% csrf_token %}

        {% for field in form %}
            <div class="form.group" >
                {% if field.errors %}
                <div class="alert alert-danger">
                    {{ field.errors }}
                </div>
                {% endif %}
                <div class="col-auto">
                    <p style="width : 400px">
                        <span>{{ field.label }}</span>
                        <span style="margin-right: 10px; float: left;">{{ field }}</span>
                    </p>
                </div>
            </div>
        {% endfor %}


        <button type="submit" class="btn btn-primary" style="margin-left: 15px;">Войти</button>
    </form>
 {% endblock %}

main/templates/main/movie_detail.html
 {% extends 'main/base.html' %}
 {% load static %}
{% block title %} {{ movie.title }} {% endblock title %}
{% block container %}
    <div class="container py-md-3">
{% endblock container %}

{% block sidebar %}
    <div class="side-bar col-lg-4">
{% endblock sidebar %}

{% block movie %}
    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="desc1-left col-md-6">
                <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent" style="outline: none; cursor: inherit;">
                        {{ movie.title }}
                </h3>
                <h5 class="editContent"></h5>
                <ul>
                    <li style="list-style: none">
                        <span><b>Год:</b> {{ movie.year }}</span>></li>
                    <li style="list-style: none">
                        <span><b>Страна:</b> {{ movie.country }}</span>
                    </li>
                    <li style="list-style: none">
                        <span><b>Слоган:</b> {{ movie.tagline }}</span>
                    </li>
                    <li style="list-style: none">
                                    <span><b>Режиссер:</b>
                     {% for director in movie.directors.all %}
                     <a href="{{ director.get_absolute_url }}">
                         {{ director.name }}
                     </a>
                     {% endfor %}
                                                        </span>
                    </li>
                    <li style="list-style: none"><span><b>Актеры:</b>
                     {% for actor in movie.actors.all %}
                     <a href="{{ actor.get_absolute_url }}">
                         {{ actor.name }}
                     </a>
                     {% endfor %}
                                </span>
                    </li>
                    <li style="list-style: none">
                                    <span>
                        <b>
                        Жанр:
                        </b>
                     {% for genre in movie.genres.all %}
                     {{ genre.name }}
                     {% endfor %}
                                    </span>
                    </li>
                    <li style="list-style: none">
                        <span><b>Премьера в мире:</b> {{ movie.world_premiere }}</span>
                    </li>
                    <li style="list-style: none">
                        <span><b>Бюджет:</b> ${{ movie.budget }}</span></li>
                    <li style="list-style: none">
                        <span><b>Сборы в США:</b> ${{ movie.fees_in_usa }}</span></li>
                    <li style="list-style: none">
                        <span><b>Сборы в мире:</b> ${{ movie.fess_in_world }}</span>
                    </li>
                    <li style="list-style: none">
                        <form action="{% url 'add_rating' %}" method="post" name="rating">
                            <b>Рейтинг:</b>
                            {% csrf_token %}
                            <input type="hidden" value="{{ movie.id }}" name="movie">
                            <span class="rating">
                                {% for k, v in star_form.fields.star.choices %}
                                    <input id="rating{{ v }}" type="radio" name="star"
                                           value="{{ k }}">
                                    <label for="rating{{ v }}">{{ k }}</label>
                                {% endfor %}
                            </span>
                            <span class="editContent">4.0</span>
                        </form>
                    </li>
                </ul>
                    <div class="share-desc">
                        <div class="share">
                            <h4 class="editContent"
                                style="outline: none; cursor: inherit;">
                            Share:
                            </h4>
                            <ul class="w3layouts_social_list list-unstyled">
                                <li>
                                    <a href="#" class="w3pvt_facebook editContent"
                                       style="outline: none; cursor: inherit;">
                                                <span class="fa fa-facebook-f"
                                                      style="outline: none; cursor: inherit;"></span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="w3pvt_twitter editContent"
                                       style="outline: none; cursor: inherit;">
                                                <span class="fa fa-twitter"
                                                      style="outline: none; cursor: inherit;"></span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="w3pvt_dribble editContent"
                                       style="outline: none; cursor: inherit;">
                                                <span class="fa fa-dribbble"
                                                      style="outline: none; cursor: inherit;"></span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="clearfix"></div>
                    </div>
            </div>
        </div>
        <div class="row sub-para-w3layouts mt-5">

            <h3 class="shop-sing editContent">
 О фильме {{ movie.title }}
            </h3>
            <br>
            <p>
 {% for image in movie.movieshots_set.all %}
                <div style="max-width: 70%; width: 70%; height: auto; margin-top: 10px; float: left; margin-left: 10px; display: inline;">
                    <img src="{{ image.image.url }}" class="img-movie-shots"
                         alt="{{ image.description }}" >
                </div>
 {% endfor %}
            </p>
            <p class="editContent" style="outline: none; cursor: inherit;">
 {{ movie.description|safe }}

        </div>
        <hr>
        <div class="row">
            <div class="single-form-left">
                <!-- contact form grid -->
                <div class="contact-single">
                    <h3 class="editContent" style="outline: none; cursor: inherit;">
                                    <span class="sub-tittle editContent"
                                          style="outline: none; cursor: inherit;">{{ movie.rewiews_set.count }}</span>Оставить
 отзыв</h3>
                    <form action="{% url 'add_review' movie.id %}" method="post" class="mt-4" id="formReview">
 {% csrf_token %}
                        <input type="hidden" name="parent" id="contactparent" value="">
                        <div class="form-group editContent">
                            <label for="contactcomment" class="editContent">
 Ваш комментарий *
                            </label>
                            <textarea class="form-control border" rows="5" name="text"
                                      id="contactcomment" required=""></textarea>
                        </div>
                        <div class="d-sm-flex">
                            <div class="col-sm-6 form-group p-0 editContent">
                                <label for="contactusername" class="editContent">
 Имя *
                                </label>
                                <input type="text" class="form-control border" name="name"
                                       id="contactusername" required="">
                            </div>
                            <div class="col-sm-6 form-group ml-sm-3 editContent">
                                <label for="contactemail" class="editContent">
                                    Email *
                                </label>
                                <input type="email" class="form-control border" name="email"
                                       id="contactemail" required="">
                            </div>
                        </div>
                        <button type="submit"
                                class="mt-3 btn btn-success btn-block py-3">
                            Отправить
                        </button>
                    </form>
                </div>
                <!--  //contact form grid ends here -->
            </div>
        </div>
        {% for review in movie.get_rewiew %}
            <div class="media py-5">
                <img src="{% static 'images/defolt.jpg' %}" class="mr-3 img-fluid" alt="image" style="width: 50px;">
                <div class="media-body mt-4">
                    <h5 class="mt-0 editContent">
                        {{ review.name }}
                    </h5>
                    <p class="mt-2 editContent">
                        {{ review.text }}
                    </p>
                    <a href="#formReview" onclick="addReview('{{ review.name }}', '{{ review.id }}')">Ответить</a>
                    {% for rew in review.rewiews_set.all %}
                        <div class="media mt-5 editContent">
                            <a class="pr-3" href="#">
                                <img src="{% static 'images/defolt.jpg' %}" class="img-fluid "
                                     alt="image" style="width: 50px">
                            </a>
                            <div class="media-body">
                                <h5 class="mt-0 editContent">{{ rew.name }}</h5>
                                <p class="mt-2 editContent">{{ rew.text }}</p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
    </div>
    </div>
        <script>
            function addReview(name, id){
            document.getElementById("contactparent").value = id;
            document.getElementById("contactcomment").innerText = `${name}, `
            }
        </script>
{% endblock movie %}

main/templates/main/movie_list.html
{% extends 'main/base.html' %}
{% block title %} {% endblock title %}
{% block header %} bg1 {% endblock header %}
{% block movie %}
    <div class="left-ads-display col-lg-9">
        <div class="row">
 {% for movie in movie_list %}
                <div class="col-md-4 product-men">
                    <div class="product-shoe-info editContent text-center mt-lg-4">
                        <div class="men-thumb-item">
                            <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
                        </div>
                        <div class="item-info-product">
                            <h4 class="">
                                <a href="{{ movie.get_absolute_url }}"
                                   class="editContent">
 {{ movie.title }}
                                </a>
                            </h4>

                            <div class="product_price">
                                <div class="grid-price">
                                    <span class="money editContent">{{ movie.tagline }}</span>
                                </div>
                            </div>
                            <ul class="stars">
                                <li><a href="#"><span class="fa fa-star"
                                                      aria-hidden="true"></span></a>
                                </li>
                                <li><a href="#"><span class="fa fa-star"
                                                      aria-hidden="true"></span></a>
                                </li>
                                <li><a href="#"><span class="fa fa-star-half-o"
                                                      aria-hidden="true"></span></a>
                                </li>
                                <li><a href="#"><span class="fa fa-star-half-o"
                                                      aria-hidden="true"></span></a>
                                </li>
                                <li><a href="#"><span class="fa fa-star-o"
                                                      aria-hidden="true"></span></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
         <div class="grid-img-right mt-4 text-right bg bg1" >
                    {% include 'include/pagination.html' %}
         </div>

    </div>
{% endblock movie %}

main/templates/main/register.html
 {% extends 'main/base.html' %}
 {% load static %}

 {% block movie %}
 <h1><span style="margin-left: 50px;">Регистрация</span></h1>

   <form action="{% url 'register' %}" method="post" style="margin-top: 70px; float: left;">
        {% csrf_token %}

        {% for field in form %}
            <div class="form.group" >
                {% if field.errors %}
                <div class="alert alert-danger">
                    {{ field.errors }}
                </div>
                {% endif %}
                <div class="col-auto">
                    <p style="width : 400px">
                        <span>{{ field.label }}</span>
                        <span style="margin-right: 10px; float: left;">{{ field }}</span>
                    </p>
                </div>
            </div>
        {% endfor %}


        <button type="submit" class="btn btn-primary" style="margin-left: 15px;">Зарегистрироваться</button>
    </form>
 {% endblock %}